baseURL = 'https://twosecretweapons.com/'
languageCode = 'en-us'
title = 'Two Secret Weapons'
theme = 'ananke'
uglyURLs = false

[params]
  description = 'Fleet Command for Bitaxe Miners'
  show_reading_time = false
  background_color_class = 'bg-black'
  mainSections = []
  recent_posts_number = 0 # Keeps the focus on your App page

[[menu.main]]
  name = 'Privacy Policy'
  url = '/privacy/'
  weight = 10

[[menu.main]]
  name = 'Remote Access'
  url = '/remote-access/'
  weight = 20

[[menu.footer]]
  name = 'Privacy Policy'
  url = '/privacy/'
  weight = 10

[[menu.footer]]
  name = 'Remote Access'
  url = '/remote-access/'
  weight = 20